/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dog.glb -o src/components/Dog.jsx --shadows 
Author: kenchoo (https://sketchfab.com/kenchoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/labrador-dog-1f56cfbab07e4fe49b5d9e521c82073a
Title: Labrador Dog
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Dog(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/dog-transformed.glb', '/draco/')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    const first = Object.values(actions)[0]
    if (first) first.reset().fadeIn(0.5).play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Dog_Armature_54">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="dog_body_53" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material} skeleton={nodes.Object_7.skeleton} morphTargetDictionary={nodes.Object_7.morphTargetDictionary} morphTargetInfluences={nodes.Object_7.morphTargetInfluences} castShadow receiveShadow />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/dog-transformed.glb', '/draco/')
