import { create } from "zustand";

const cloneSection = (section) => ({ ...section });

export const ECCTRL_TUNING_PRESETS = {
  vehicle1: {
    common: {
      jumpVelocity: 4,
      speedMultiplier: 1,
      boostMultiplier: 1,
      cameraDistance: 3,
      cameraHeight: 0.5,
      cameraSmoothTime: 0.1,
      cameraTurnSpeed: 5,
    },
    board: {
      speedMultiplier: 1,
      bodyDensity: 1,
      bodyHalfWidth: 1,
      bodyHalfHeight: 0.4,
      bodyHalfLength: 2.4,
      bodyPosY: 0.55,
      wheelOffsetX: 0.9,
      wheelOffsetY: 0,
      wheelOffsetZ: 1.8,
      rayShapeR: 0.5,
      rayShapeH: 0.15,
      rayLength: 0.5,
      springK: 38000,
      dampingC: 4000,
      maxBrakeTorque: 7000,
      frontMaxBrakeTorque: 7000,
      rearMaxBrakeTorque: 5600,
      rearDriveTorqueWeight: 1,
      tireGripFactor: 3,
      engineHorsepower: 600,
      engineMaxRPM: 6000,
      finalDriveRatio: 1,
      steerRate: Math.PI * 2,
      maxSteerAngle: Math.PI / 6,
      shiftUpRPM: 5200,
      shiftDownRPM: 2200,
      shiftCooldown: 0.35,
      reverseTorqueScale: 1,
      reverseRPMScale: 0.5,
      showWheelModel: false,
      debugWheel: false,
    },
    car: {
      bodyDensity: 1,
      bodyHalfWidth: 1,
      bodyHalfHeight: 0.4,
      bodyHalfLength: 2.4,
      bodyPosY: 0.55,
      wheelOffsetX: 0.9,
      wheelOffsetY: 0,
      wheelOffsetZ: 1.8,
      rayShapeR: 0.5,
      rayShapeH: 0.15,
      rayLength: 0.5,
      springK: 38000,
      dampingC: 4000,
      maxBrakeTorque: 7000,
      frontMaxBrakeTorque: 7000,
      rearMaxBrakeTorque: 5600,
      rearDriveTorqueWeight: 1,
      tireGripFactor: 3,
      engineHorsepower: 600,
      engineMaxRPM: 6000,
      finalDriveRatio: 1,
      steerRate: Math.PI * 2,
      maxSteerAngle: Math.PI / 6,
      shiftUpRPM: 5200,
      shiftDownRPM: 2200,
      shiftCooldown: 0.35,
      reverseTorqueScale: 1,
      reverseRPMScale: 0.5,
      showWheelModel: false,
      debugWheel: false,
    },
    drone: {
      bodyDensity: 1,
      bodyHalfWidth: 0.4,
      bodyHalfHeight: 0.2,
      bodyHalfLength: 1.5,
      propellerOffsetX: 1,
      propellerOffsetY: -0.15,
      propellerOffsetZ: 1,
      maxThrust: 5000,
      torqueRatio: 0.6,
      maxYawRate: 2,
      maxHorizSpeed: 20,
      maxVertSpeed: 8,
      maxTiltAngle: Math.PI / 4,
      airDragFactor: 0.2,
      TILT_P: 15,
      TILT_D: 3,
      YAW_P: 4,
      VERT_POS_P: 900,
      VERT_POS_D: 700,
      HORIZ_POS_P: 500,
      HORIZ_POS_D: 550,
      HORIZ_VEL_P: 1,
      VERT_VEL_P: 2,
      showPropellerModel: false,
      debugPropeller: false,
    },
  },
  vehicle2: {
    common: {
      jumpVelocity: 9,
      speedMultiplier: 2.2,
      boostMultiplier: 1.25,
      cameraDistance: 3,
      cameraHeight: 0.45,
      cameraSmoothTime: 0.1,
      cameraTurnSpeed: 4.2,
    },
    board: {
      speedMultiplier: 1,
      bodyDensity: 1,
      bodyHalfWidth: 1,
      bodyHalfHeight: 0.3,
      bodyHalfLength: 2.4,
      bodyPosY: 0.55,
      wheelOffsetX: 0.85,
      wheelOffsetY: 0,
      wheelOffsetZ: 1.5,
      rayShapeR: 0.5,
      rayShapeH: 0.15,
      rayLength: 0.5,
      springK: 42000,
      dampingC: 7000,
      maxBrakeTorque: 7000,
      frontMaxBrakeTorque: 7000,
      rearMaxBrakeTorque: 5600,
      rearDriveTorqueWeight: 1,
      tireGripFactor: 3,
      engineHorsepower: 900,
      engineMaxRPM: 6000,
      finalDriveRatio: 1.75,
      steerRate: Math.PI * 3,
      maxSteerAngle: Math.PI / 8,
      shiftUpRPM: 5200,
      shiftDownRPM: 2200,
      shiftCooldown: 0.35,
      reverseTorqueScale: 1,
      reverseRPMScale: 0.5,
      showWheelModel: false,
      debugWheel: false,
    },
    car: {
      bodyDensity: 1,
      bodyHalfWidth: 1,
      bodyHalfHeight: 0.3,
      bodyHalfLength: 2.4,
      bodyPosY: 0.55,
      wheelOffsetX: 0.85,
      wheelOffsetY: 0,
      wheelOffsetZ: 1.5,
      rayShapeR: 0.5,
      rayShapeH: 0.15,
      rayLength: 0.5,
      springK: 42000,
      dampingC: 7000,
      maxBrakeTorque: 7000,
      frontMaxBrakeTorque: 7000,
      rearMaxBrakeTorque: 5600,
      rearDriveTorqueWeight: 1,
      tireGripFactor: 3,
      engineHorsepower: 900,
      engineMaxRPM: 6000,
      finalDriveRatio: 1.75,
      steerRate: Math.PI * 3,
      maxSteerAngle: Math.PI / 8,
      shiftUpRPM: 5200,
      shiftDownRPM: 2200,
      shiftCooldown: 0.35,
      reverseTorqueScale: 1,
      reverseRPMScale: 0.5,
      showWheelModel: false,
      debugWheel: false,
    },
    drone: {
      bodyDensity: 1,
      bodyHalfWidth: 0.4,
      bodyHalfHeight: 0.2,
      bodyHalfLength: 1.5,
      propellerOffsetX: 1,
      propellerOffsetY: -0.15,
      propellerOffsetZ: 1,
      maxThrust: 5000,
      torqueRatio: 0.6,
      maxYawRate: 2,
      maxHorizSpeed: 20,
      maxVertSpeed: 8,
      maxTiltAngle: Math.PI / 4,
      airDragFactor: 0.2,
      TILT_P: 15,
      TILT_D: 3,
      YAW_P: 4,
      VERT_POS_P: 900,
      VERT_POS_D: 700,
      HORIZ_POS_P: 500,
      HORIZ_POS_D: 550,
      HORIZ_VEL_P: 1,
      VERT_VEL_P: 2,
      showPropellerModel: false,
      debugPropeller: false,
    },
  },
  drone: {
    common: {
      jumpVelocity: 10,
      speedMultiplier: 2.5,
      boostMultiplier: 1.45,
      cameraDistance: 3,
      cameraHeight: 0.5,
      cameraSmoothTime: 0.1,
      cameraTurnSpeed: 5,
    },
    board: {
      speedMultiplier: 1,
      bodyDensity: 1,
      bodyHalfWidth: 1,
      bodyHalfHeight: 0.4,
      bodyHalfLength: 2.4,
      bodyPosY: 0.55,
      wheelOffsetX: 0.9,
      wheelOffsetY: 0,
      wheelOffsetZ: 1.8,
      rayShapeR: 0.5,
      rayShapeH: 0.15,
      rayLength: 0.5,
      springK: 46000,
      dampingC: 5400,
      maxBrakeTorque: 5200,
      frontMaxBrakeTorque: 5200,
      rearMaxBrakeTorque: 4200,
      rearDriveTorqueWeight: 1,
      tireGripFactor: 2.1,
      engineHorsepower: 720,
      engineMaxRPM: 6000,
      finalDriveRatio: 1.75,
      steerRate: Math.PI * 3,
      maxSteerAngle: Math.PI / 8,
      shiftUpRPM: 5200,
      shiftDownRPM: 2200,
      shiftCooldown: 0.35,
      reverseTorqueScale: 1,
      reverseRPMScale: 0.5,
      showWheelModel: false,
      debugWheel: false,
    },
    car: {
      bodyDensity: 1,
      bodyHalfWidth: 1,
      bodyHalfHeight: 0.4,
      bodyHalfLength: 2.4,
      bodyPosY: 0.55,
      wheelOffsetX: 0.9,
      wheelOffsetY: 0,
      wheelOffsetZ: 1.8,
      rayShapeR: 0.5,
      rayShapeH: 0.15,
      rayLength: 0.5,
      springK: 46000,
      dampingC: 5400,
      maxBrakeTorque: 5200,
      frontMaxBrakeTorque: 5200,
      rearMaxBrakeTorque: 4200,
      rearDriveTorqueWeight: 1,
      tireGripFactor: 2.1,
      engineHorsepower: 720,
      engineMaxRPM: 6000,
      finalDriveRatio: 1.75,
      steerRate: Math.PI * 3,
      maxSteerAngle: Math.PI / 8,
      shiftUpRPM: 5200,
      shiftDownRPM: 2200,
      shiftCooldown: 0.35,
      reverseTorqueScale: 1,
      reverseRPMScale: 0.5,
      showWheelModel: false,
      debugWheel: false,
    },
    drone: {
      bodyDensity: 1,
      bodyHalfWidth: 0.4,
      bodyHalfHeight: 0.2,
      bodyHalfLength: 1.5,
      propellerOffsetX: 1,
      propellerOffsetY: -0.15,
      propellerOffsetZ: 1,
      maxThrust: 5000,
      torqueRatio: 0.6,
      maxYawRate: 2,
      maxHorizSpeed: 20,
      maxVertSpeed: 8,
      maxTiltAngle: Math.PI / 4,
      airDragFactor: 0.2,
      TILT_P: 15,
      TILT_D: 3,
      YAW_P: 4,
      VERT_POS_P: 900,
      VERT_POS_D: 700,
      HORIZ_POS_P: 500,
      HORIZ_POS_D: 550,
      HORIZ_VEL_P: 1,
      VERT_VEL_P: 2,
      showPropellerModel: false,
      debugPropeller: false,
    },
  },
};

ECCTRL_TUNING_PRESETS.car = ECCTRL_TUNING_PRESETS.vehicle1;

export const ECCTRL_VEHICLE_TUNING_PRESETS = {
  longboard: "car",
  skateboard: "car",
  surfboard_lucid_sn1: "drone",
  arcadiaBoard: "car",
  goKart: "car",
  ufo: "drone",
};

export function getEcctrlTuningPreset(name = "vehicle1") {
  const preset = ECCTRL_TUNING_PRESETS[name] || ECCTRL_TUNING_PRESETS.car || ECCTRL_TUNING_PRESETS.vehicle1;
  return {
    common: cloneSection(preset.common),
    board: cloneSection(preset.board),
    car: cloneSection(preset.car),
    drone: cloneSection(preset.drone),
  };
}

export const DEFAULT_ECCTRL_TUNING = {
  ...getEcctrlTuningPreset("vehicle1"),
};

export const useEcctrlTuningStore = create((set) => ({
  ...DEFAULT_ECCTRL_TUNING,
  setTuning: (next) =>
    set((state) => ({
      common: next.common ? { ...state.common, ...next.common } : state.common,
      board: next.board ? { ...state.board, ...next.board } : state.board,
      car: next.car ? { ...state.car, ...next.car } : state.car,
      drone: next.drone ? { ...state.drone, ...next.drone } : state.drone,
    })),
}));
