import { create } from "zustand";

export const DEFAULT_ECCTRL_TUNING = {
  common: {
    jumpVelocity: 10,
    speedMultiplier: 2.5,
    cameraDistance: 3,
    cameraHeight: 0.5,
    cameraSmoothTime: 0.1,
    cameraTurnSpeed: 5,
  },
  board: {
    speedMultiplier: 1.35,
    bodyDensity: 120,
    bodyHalfWidth: 1.4,
    bodyHalfHeight: 0.22,
    bodyHalfLength: 2.1,
    bodyPosY: 0.0,
    wheelOffsetX: 1.05,
    wheelOffsetY: 0,
    wheelOffsetZ: 1.7,
    rayShapeR: 0.45,
    rayShapeH: 0.12,
    rayLength: 0.42,
    springK: 52000,
    dampingC: 6200,
    maxBrakeTorque: 3800,
    tireGripFactor: 2.2,
    engineHorsepower: 900,
    engineMaxRPM: 6500,
    finalDriveRatio: 1.4,
    steerRate: Math.PI * 1.4,
    maxSteerAngle: Math.PI / 10,
    shiftUpRPM: 5200,
    shiftDownRPM: 2200,
    shiftCooldown: 0.35,
    reverseTorqueScale: 1,
    reverseRPMScale: 0.5,
    showWheelModel: false,
    debugWheel: false,
  },
  car: {
    bodyDensity: 200,
    bodyHalfWidth: 1,
    bodyHalfHeight: 0.4,
    bodyHalfLength: 2.4,
    bodyPosY: 0.1,
    wheelOffsetX: 0.85,
    wheelOffsetY: 0,
    wheelOffsetZ: 1.5,
    rayShapeR: 0.5,
    rayShapeH: 0.15,
    rayLength: 0.5,
    springK: 38000,
    dampingC: 4000,
    maxBrakeTorque: 3000,
    tireGripFactor: 1.3,
    engineHorsepower: 600,
    engineMaxRPM: 6000,
    finalDriveRatio: 1,
    steerRate: Math.PI * 2,
    maxSteerAngle: Math.PI / 6,
    shiftUpRPM: 5200,
    shiftDownRPM: 2200,
    shiftCooldown: 0.35,
    reverseTorqueScale: 1,
    reverseRPMScale: 0.5,
    showWheelModel: false,
    debugWheel: false,
  },
  drone: {
    bodyDensity: 200,
    bodyHalfWidth: 0.4,
    bodyHalfHeight: 0.2,
    bodyHalfLength: 1.5,
    propellerOffsetX: 1,
    propellerOffsetY: -0.15,
    propellerOffsetZ: 1,
    maxThrust: 5000,
    torqueRatio: 0.6,
    maxYawRate: 2,
    maxHorizSpeed: 20,
    maxVertSpeed: 8,
    maxTiltAngle: Math.PI / 4,
    airDragFactor: 0.2,
    TILT_P: 15,
    TILT_D: 3,
    YAW_P: 4,
    VERT_POS_P: 900,
    VERT_POS_D: 700,
    HORIZ_POS_P: 500,
    HORIZ_POS_D: 550,
    HORIZ_VEL_P: 1,
    VERT_VEL_P: 2,
    showPropellerModel: false,
    debugPropeller: false,
  },
};

export const useEcctrlTuningStore = create((set) => ({
  ...DEFAULT_ECCTRL_TUNING,
  setTuning: (next) =>
    set((state) => ({
      common: next.common ? { ...state.common, ...next.common } : state.common,
      board: next.board ? { ...state.board, ...next.board } : state.board,
      car: next.car ? { ...state.car, ...next.car } : state.car,
      drone: next.drone ? { ...state.drone, ...next.drone } : state.drone,
    })),
}));
